import BDO_COMPANY from "./generated/bdo-valuation.js";

export const PHILIPPINE_ASSUMPTIONS = {
  valuationDate: "17 Jul 2026",
  localGovernmentYield: 0.07052,
  grahamBaselineYield: 0.06,
  corporateTaxReference: 0.25,
  sourceLabel: "Bureau of the Treasury - 10-year T-bond auction, 23 Jun 2026",
  sourceUrl:
    "https://www.treasury.gov.ph/wp-content/uploads/2026/06/Treasury-Bonds-Auction-Result-on-23-June-2026-.pdf",
  note:
    "The 7.052% figure is a local government-bond yield, not a default-free CAPM rate. Production cost of equity must separately identify the sovereign default adjustment, mature-market ERP, Philippine country-risk premium, beta, and source dates.",
};

export const SOURCE_LINKS = {
  valuation: {
    label: "Valuation-Models.xlsx",
    href: "./Valuation-Models.xlsx",
  },
  health: {
    label: "Financial Health Metrics.pdf",
    href: "./Financial%20Health%20Metrics.pdf",
  },
};

export const INDUSTRIAL_COMPANIES = [
  {
    symbol: "AP",
    name: "Aboitiz Power Corporation",
    shortName: "AboitizPower",
    sector: "Industrial",
    subsector: "Power generation & distribution",
    color: "#2563eb",
    dataConfidence: 0.96,
    insight: "Scale leader; leverage and the 2025 EPS decline are the main checks.",
    source: {
      label: "2025 Aboitiz Integrated Report - AboitizPower statements, pp. 158-165",
      href: "./PH-Stocks/Industrial/Aboitiz%20Financial%20Statements/2025%20Aboitiz%20Integrated%20Report.pdf#page=80",
    },
    financials: {
      period: "FY 2025",
      revenue: 198_479_280_000,
      grossProfit: null,
      operatingIncome: 37_505_708_000,
      generalAdmin: 15_600_137_000,
      interestExpense: 17_987_956_000,
      pretaxIncome: 29_080_876_000,
      taxExpense: 6_619_884_000,
      netIncome: 22_460_992_000,
      parentNetIncome: 19_450_127_000,
      cash: 58_932_061_000,
      debt: 327_548_364_000,
      liabilities: 408_157_678_000,
      equity: 214_640_174_000,
      retainedEarnings: 187_239_124_000,
      retainedEarningsPrevious: 184_782_755_000,
      treasuryStock: 4_891_831_000,
      preferredStock: 0,
      eps: 2.7,
      epsPrevious: 4.7,
      shares: 7_203_750_741,
      operatingCashFlow: 51_722_480_000,
    },
    // Optional earlier annual periods and standalone quarters can be added here.
    // The current `financials` snapshot is included automatically as FY 2025.
    financialHistory: { annual: [], quarterly: [] },
    valuation: {
      normalizedFcf: 38_000_000_000,
      fcfGrowth: 0.035,
      discountRate: 0.115,
      terminalGrowth: 0.035,
      epsGrowthPercent: 4,
      peerPe: 11,
      dividendPerShare: 1.9,
      dividendGrowth: 0.03,
      dividendDiscountRate: 0.105,
      cashFlowType: "fcff",
      cashFlowSource: "internal_estimate",
      bridgeComplete: false,
      modelPolicy: {
        primary: "dcf",
        crossChecks: ["multiples", "ddm"],
        publishable: true,
        reason: "Consolidated FCFF DCF is the primary screen; multiples and DDM are separate cross-checks.",
        warnings: ["Preliminary only until the FCFF schedule and full equity bridge tie to filings."],
      },
      note: "Normalized FCF smooths project timing; use reported cash flow and debt schedules in production.",
    },
  },
  {
    symbol: "SCC",
    name: "Semirara Mining and Power Corporation",
    shortName: "Semirara",
    sector: "Industrial",
    subsector: "Integrated coal & power",
    color: "#0f766e",
    dataConfidence: 0.98,
    insight: "Cash exceeds debt and margins remain strong; earnings fell year on year.",
    source: {
      label: "Semirara 2025 SEC Form 17-A - consolidated statements, pp. 140-143",
      href: "./PH-Stocks/Industrial/Semirara%20Financial%20Statements/MSRD%20SEC%20Form%2017A%202025%20Amended%20Semirara%20Mining%20and%20Power%20Corporation%2020April2026.pdf#page=140",
    },
    financials: {
      period: "FY 2025",
      revenue: 52_232_196_279,
      grossProfit: 21_362_757_434,
      operatingIncome: 14_167_377_047,
      generalAdmin: 7_195_380_387,
      interestExpense: 204_977_442,
      pretaxIncome: 14_723_762_616,
      taxExpense: 1_663_573_558,
      netIncome: 13_060_189_058,
      parentNetIncome: 13_060_189_058,
      cash: 4_363_886_635,
      debt: 996_694_792,
      liabilities: 10_711_462_115,
      equity: 55_781_748_831,
      retainedEarnings: 45_723_794_480,
      retainedEarningsPrevious: 46_477_885_187,
      treasuryStock: 739_526_678,
      preferredStock: 0,
      eps: 3.07,
      epsPrevious: 4.62,
      shares: 4_254_133_244,
      operatingCashFlow: 16_434_115_891,
    },
    financialHistory: { annual: [], quarterly: [] },
    valuation: {
      normalizedFcf: 11_000_000_000,
      fcfGrowth: 0.02,
      discountRate: 0.115,
      terminalGrowth: 0.025,
      epsGrowthPercent: 3,
      peerPe: 9,
      dividendPerShare: 3.24,
      dividendGrowth: 0.01,
      dividendDiscountRate: 0.11,
      cashFlowType: "fcff",
      cashFlowSource: "internal_estimate",
      bridgeComplete: false,
      modelPolicy: {
        primary: "finite_life_nav",
        crossChecks: ["dcf", "multiples"],
        publishable: false,
        reason: "Coal reserves are finite and commodity-linked; a reserve-life NAV is required.",
        blockReason: "the required finite-life mining NAV is not yet implemented",
      },
      note: "Normalized FCF tempers the commodity cycle and excludes a one-year peak assumption.",
    },
  },
  {
    symbol: "ACR",
    name: "Alsons Consolidated Resources, Inc.",
    shortName: "Alsons",
    sector: "Industrial",
    subsector: "Power generation & property",
    color: "#7c3aed",
    dataConfidence: 0.95,
    insight: "Revenue and parent EPS improved, but leverage and finance costs are elevated.",
    source: {
      label: "Alsons 2025 SEC Form 17-A - consolidated statements, pp. 63-69",
      href: "./PH-Stocks/Industrial/Alsons%20Financial%20Statements/2026-04-15%20ACR%2017A_2025_Final_compressed.pdf#page=63",
    },
    financials: {
      period: "FY 2025",
      revenue: 14_942_499_489,
      grossProfit: 5_877_292_358,
      operatingIncome: 4_514_084_326,
      generalAdmin: 1_363_308_032,
      interestExpense: 2_049_670_811,
      pretaxIncome: 2_934_529_423,
      taxExpense: 497_228_669,
      netIncome: 2_437_300_754,
      parentNetIncome: 799_810_619,
      cash: 2_806_074_979,
      debt: 28_553_293_368,
      liabilities: 33_777_453_774,
      equity: 18_784_624_535,
      retainedEarnings: 5_391_063_896,
      retainedEarningsPrevious: 4_721_483_277,
      treasuryStock: 0,
      preferredStock: 0,
      eps: 0.126,
      epsPrevious: 0.114,
      shares: 6_347_703_325,
      operatingCashFlow: 4_792_812_561,
    },
    financialHistory: { annual: [], quarterly: [] },
    valuation: {
      normalizedFcf: 3_359_294_057,
      fcfGrowth: 0.035,
      discountRate: 0.125,
      terminalGrowth: 0.03,
      epsGrowthPercent: 6,
      peerPe: 10,
      dividendPerShare: 0.0205,
      dividendGrowth: 0.03,
      dividendDiscountRate: 0.12,
      cashFlowType: "fcff",
      cashFlowSource: "internal_estimate",
      bridgeComplete: false,
      modelPolicy: {
        primary: "dcf",
        crossChecks: ["multiples"],
        publishable: true,
        reason: "FCFF DCF is the primary screen; peer P/E is a separate reasonableness check.",
        warnings: ["Preliminary only until capex, debt, tax, and minority-interest schedules are tied out."],
      },
      note: "Base FCF is 2025 operating cash flow less reported additions to property and equipment.",
    },
  },
  {
    symbol: "PERC",
    name: "PetroEnergy Resources Corporation",
    shortName: "PetroEnergy",
    sector: "Industrial",
    subsector: "Renewables & upstream energy",
    color: "#c2410c",
    dataConfidence: 0.93,
    insight: "Revenue grew, while lower oil income and project debt pressured returns.",
    source: {
      label: "PetroEnergy 2025 SEC Form 17-A - MD&A financial tables, pp. 30 and 34",
      href: "./PH-Stocks/Industrial/PetroEnergy%20Financial%20Statements/PERC%20SEC%2017-A%202025.pdf#page=30",
    },
    financials: {
      period: "FY 2025",
      revenue: 3_724_205_637,
      grossProfit: 1_571_315_876,
      operatingIncome: 1_158_066_618,
      generalAdmin: 413_249_258,
      interestExpense: 652_655_083,
      pretaxIncome: 672_887_431,
      taxExpense: 54_554_306,
      netIncome: 618_333_125,
      parentNetIncome: 284_178_362,
      cash: 1_791_498_636,
      debt: 9_431_852_000,
      liabilities: 11_580_457_887,
      equity: 14_133_667_727,
      retainedEarnings: null,
      retainedEarningsPrevious: null,
      treasuryStock: 0,
      preferredStock: 0,
      eps: 0.5,
      epsPrevious: 0.83,
      shares: 568_356_724,
      operatingCashFlow: null,
    },
    financialHistory: { annual: [], quarterly: [] },
    valuation: {
      normalizedFcf: 1_050_000_000,
      fcfGrowth: 0.05,
      discountRate: 0.13,
      terminalGrowth: 0.03,
      epsGrowthPercent: 5,
      peerPe: 11,
      dividendPerShare: null,
      dividendGrowth: 0.02,
      dividendDiscountRate: 0.12,
      cashFlowType: "fcff",
      cashFlowSource: "internal_estimate",
      bridgeComplete: false,
      modelPolicy: {
        primary: "sotp",
        crossChecks: ["dcf", "multiples"],
        publishable: false,
        reason: "Renewables and upstream assets require asset-level cash flows and different risk assumptions.",
        blockReason: "the required sum-of-the-parts valuation is not yet implemented",
      },
      note: "Normalized FCF is illustrative while new renewable projects are in a heavy build-out phase.",
    },
  },
];

export const VALUATION_COMPANIES = [...INDUSTRIAL_COMPANIES, BDO_COMPANY];

export const FILING_NEWS = [
  {
    id: "ap-earnings",
    symbol: "AP",
    scope: "Company",
    date: "FY 2025 filing",
    title: "Revenue held steady, but net income reset lower",
    summary:
      "AboitizPower reported PHP198.5B of operating revenue and PHP22.5B of net income. Impairment and higher financing costs were the main pressure points.",
    tag: "Earnings",
  },
  {
    id: "scc-mix",
    symbol: "SCC",
    scope: "Company",
    date: "FY 2025 filing",
    title: "Power revenue stayed resilient as coal revenue softened",
    summary:
      "Semirara's combined revenue fell to PHP52.2B, but cash still covered reported debt more than four times at year-end.",
    tag: "Business mix",
  },
  {
    id: "acr-growth",
    symbol: "ACR",
    scope: "Company",
    date: "FY 2025 filing",
    title: "Top line and parent EPS moved higher",
    summary:
      "Alsons grew revenue to PHP14.9B and parent EPS to PHP0.126. Financing charges rose to PHP2.0B, keeping leverage in focus.",
    tag: "Earnings",
  },
  {
    id: "perc-buildout",
    symbol: "PERC",
    scope: "Company",
    date: "FY 2025 filing",
    title: "Renewable build-out lifted sales and capital needs",
    summary:
      "Electricity sales rose 11.5%, while oil revenue fell 20.2%. New projects expanded the asset base and increased financing pressure.",
    tag: "Projects",
  },
  {
    id: "sector-rates",
    symbol: "ALL",
    scope: "Sector",
    date: "23 Jun 2026",
    title: "A 7.052% long-bond proxy raises the valuation hurdle",
    summary:
      "The latest accepted 9.7-year Treasury auction reviewed cleared at a 7.052% average yield. Higher required returns make leverage and cash conversion more important.",
    tag: "Rates",
  },
  {
    id: "sector-capex",
    symbol: "ALL",
    scope: "Sector",
    date: "FY 2025 filings",
    title: "Industrial energy names are trading cash today for capacity tomorrow",
    summary:
      "Across the test group, project spending supports future generation but makes free cash flow and debt service the clearest near-term watch items.",
    tag: "Sector view",
  },
];
