#!/usr/bin/env python3
"""Transform the parsed BDO corpus into model and FinSight UI inputs.

This script deliberately selects filing facts by issuer period, canonical key,
statement page, raw label, and period hint. It does not use the parser's global
"best candidate" for valuation-period selection.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PARSER_OUTPUT = ROOT / "output" / "fs-testing" / "bdo"
CORPUS = PARSER_OUTPUT / "corpora" / "BDO"
FRONTEND_OUTPUT = (
    ROOT / "frontend" / "src" / "research" / "generated" / "bdo-valuation.js"
)
VALUATION_OUTPUT = PARSER_OUTPUT / "valuation-result.json"
sys.path.insert(0, str(ROOT / "backend"))

from app.valuation.assumptions import PH, cost_of_equity  # noqa: E402
from app.valuation.bank import residual_income_valuation  # noqa: E402


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def write_javascript_module(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    payload = json.dumps(value, indent=2, ensure_ascii=False)
    temporary.write_text(
        f"// Generated by scripts/build_bdo_valuation_pipeline.py.\n"
        f"// Do not edit by hand; regenerate from the filing corpus.\n"
        f"export default {payload};\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def source_record(fact: dict[str, Any], document: dict[str, Any]) -> dict[str, Any]:
    return {
        "filing_period": document["period"],
        "filename": document["filename"],
        "document_sha256": document["sha256"],
        "page": fact["source"]["page"],
        "line": fact["source"]["line"],
        "raw_label": fact["raw_label"],
        "raw_text": fact["raw_text"],
        "confidence": fact["confidence"],
        "candidate_kind": fact["candidate_kind"],
    }


def main() -> int:
    inventory = read_json(PARSER_OUTPUT / "inventory.json")
    facts_index = read_json(CORPUS / "facts.json")
    requirements = read_json(CORPUS / "requirements.json")
    documents = {
        item["sha256"]: item
        for item in inventory["documents"]
        if item.get("processed")
    }
    facts = list(facts_index["facts"])

    if requirements["routing"]["subsector"] != "banks":
        raise RuntimeError("BDO did not route to the Banks subsector")
    if requirements["summary"]["missing_required"]:
        raise RuntimeError(
            "Parser still has missing required BDO fields: "
            + ", ".join(requirements["summary"]["missing_required"])
        )

    def candidates(
        key: str,
        filing_period: str,
        *,
        page: int | None = None,
        label_contains: str | None = None,
        alias_contains: str | None = None,
        candidate_kind: str | None = None,
    ) -> list[tuple[dict[str, Any], dict[str, Any]]]:
        rows = []
        for fact in facts:
            document = documents.get(fact["source"]["document_sha256"])
            if not document or document["period"] != filing_period:
                continue
            if fact.get("canonical_key") != key:
                continue
            if page is not None and fact["source"]["page"] != page:
                continue
            if label_contains and label_contains.lower() not in fact["raw_label"].lower():
                continue
            if alias_contains and alias_contains.lower() not in str(
                fact.get("matched_alias", "")
            ).lower():
                continue
            if candidate_kind and fact.get("candidate_kind") != candidate_kind:
                continue
            rows.append((fact, document))
        return rows

    def exact_value(
        key: str,
        filing_period: str,
        *,
        page: int,
        label_contains: str,
        period_hint: str | None = None,
        alias_contains: str | None = None,
        candidate_kind: str | None = None,
        choose: str = "first",
        minimum: float | None = None,
    ) -> tuple[float, dict[str, Any]]:
        rows = candidates(
            key,
            filing_period,
            page=page,
            label_contains=label_contains,
            alias_contains=alias_contains,
            candidate_kind=candidate_kind,
        )
        if not rows:
            raise RuntimeError(
                f"No fact for {key}, {filing_period}, p.{page}, {label_contains!r}"
            )
        fact, document = max(rows, key=lambda row: row[0]["confidence"])
        values = [
            value
            for value in fact["values"]
            if isinstance(value.get("normalized_value"), (int, float))
            and math.isfinite(value["normalized_value"])
            and (period_hint is None or value.get("period_hint") == period_hint)
            and (minimum is None or abs(value["normalized_value"]) >= minimum)
        ]
        if not values:
            raise RuntimeError(
                f"No usable value for {key}, {filing_period}, hint={period_hint}"
            )
        if choose == "largest":
            selected = max(values, key=lambda value: abs(value["normalized_value"]))
        else:
            selected = values[0]
        return float(selected["normalized_value"]), source_record(fact, document)

    # Latest balance-sheet inputs at 30 June 2026.
    parent_equity, parent_equity_source = exact_value(
        "parent_equity",
        "Q2 2026",
        page=5,
        label_contains="Shareholders of the Parent Bank",
        period_hint="June 30, 2026",
    )
    total_equity, total_equity_source = exact_value(
        "total_equity",
        "Q2 2026",
        page=5,
        label_contains="Total Equity",
        period_hint="June 30, 2026",
    )
    total_assets, total_assets_source = exact_value(
        "total_assets",
        "Q2 2026",
        page=5,
        label_contains="Total Resources",
        period_hint="June 30, 2026",
    )
    total_liabilities, total_liabilities_source = exact_value(
        "total_liabilities",
        "Q2 2026",
        page=5,
        label_contains="Total Liabilities",
        period_hint="June 30, 2026",
    )
    deposits, deposits_source = exact_value(
        "customer_deposits",
        "Q2 2026",
        page=5,
        label_contains="Total Deposit Liabilities",
        period_hint="June 30, 2026",
    )
    net_loans, net_loans_source = exact_value(
        "gross_loans",
        "Q2 2026",
        page=5,
        label_contains="Loans and Other Receivables",
        period_hint="June 30, 2026",
        minimum=1_000_000_000,
    )
    gross_loans, gross_loans_source = exact_value(
        "gross_loans",
        "Q2 2026",
        page=21,
        label_contains="B. LOANS AND RECEIVABLES",
        choose="largest",
        minimum=1_000_000_000_000,
    )
    allowance_credit_losses = gross_loans - net_loans
    if allowance_credit_losses <= 0:
        raise RuntimeError(
            "Derived credit-loss allowance must reconcile gross loans above net loans"
        )
    cash, cash_source = exact_value(
        "cash",
        "Q2 2026",
        page=5,
        label_contains="Cash and Other Cash Items",
        period_hint="June 30, 2026",
    )
    shares, shares_source = exact_value(
        "shares_outstanding",
        "Q2 2026",
        page=2,
        label_contains="Common Stock",
        choose="largest",
        minimum=1_000_000_000,
    )

    # Preferred shares are disclosed as 618m shares at PHP10 par. Par capital is
    # deducted from parent equity to obtain common book equity.
    preferred_shares, preferred_source = exact_value(
        "preferred_equity",
        "FY2025",
        page=2,
        label_contains="Preferred Stock",
        choose="largest",
        minimum=100_000_000,
    )
    preferred_par_value = 10.0
    preferred_par_capital = preferred_shares * preferred_par_value
    common_equity = parent_equity - preferred_par_capital
    book_value_per_share = common_equity / shares

    q2_2025_parent_equity, q2_2025_equity_source = exact_value(
        "parent_equity",
        "Q2 2025",
        page=5,
        label_contains="Shareholders of the Parent Bank",
        period_hint="June 30, 2025",
    )
    beginning_common_equity = q2_2025_parent_equity - preferred_par_capital

    # TTM parent earnings = FY2025 parent earnings + H1 2026 - H1 2025.
    fy2025_parent_income, fy2025_income_source = exact_value(
        "parent_net_income",
        "FY2025",
        page=82,
        label_contains="Parent Company of",
        alias_contains="parent company of",
        minimum=10_000_000_000,
    )
    h1_2026_parent_income, h1_2026_income_source = exact_value(
        "parent_net_income",
        "Q2 2026",
        page=6,
        label_contains="Shareholders of the Parent Bank",
        period_hint="6M 2026 YTD",
    )
    h1_2025_parent_income, h1_2025_income_source = exact_value(
        "parent_net_income",
        "Q2 2026",
        page=6,
        label_contains="Shareholders of the Parent Bank",
        period_hint="6M 2025 YTD",
    )
    ttm_parent_income = (
        fy2025_parent_income + h1_2026_parent_income - h1_2025_parent_income
    )
    average_common_equity = (beginning_common_equity + common_equity) / 2
    ttm_roe = ttm_parent_income / average_common_equity
    ttm_eps = ttm_parent_income / shares

    # TTM net interest income uses the same non-overlapping construction.
    fy2025_net_interest_income, fy2025_nii_source = exact_value(
        "net_interest_income",
        "FY2025",
        page=82,
        label_contains="net interest income",
        candidate_kind="prose_window",
        minimum=100_000_000_000,
    )
    h1_2026_net_interest_income, h1_2026_nii_source = exact_value(
        "net_interest_income",
        "Q2 2026",
        page=6,
        label_contains="NET INTEREST INCOME",
        period_hint="6M 2026 YTD",
    )
    h1_2025_net_interest_income, h1_2025_nii_source = exact_value(
        "net_interest_income",
        "Q2 2026",
        page=6,
        label_contains="NET INTEREST INCOME",
        period_hint="6M 2025 YTD",
    )
    ttm_net_interest_income = (
        fy2025_net_interest_income
        + h1_2026_net_interest_income
        - h1_2025_net_interest_income
    )

    dividends_paid, dividends_paid_source = exact_value(
        "dividends_paid",
        "Q2 2026",
        page=9,
        label_contains="Dividends paid",
        period_hint="2026",
    )

    # FY2025 declared common DPS was PHP1.00 in Q1 and PHP1.10 in Q2-Q4.
    # H1 2026 cash dividends less the annual preferred dividend imply PHP2.20
    # common DPS; therefore the latest TTM common DPS is PHP4.40.
    declared_dps_fact = candidates(
        "dividends_per_share",
        "FY2025",
        page=79,
        label_contains="quarterly cash dividends",
    )
    if not declared_dps_fact:
        raise RuntimeError("FY2025 common dividend declaration was not extracted")
    fy2025_dps_source = source_record(*declared_dps_fact[0])
    ttm_dividend_per_share = 4.40
    current_payout_ratio = ttm_dividend_per_share / ttm_eps

    cet1, cet1_source = exact_value(
        "cet1_ratio",
        "FY2025",
        page=88,
        label_contains="CET1 ratio",
    )
    car, car_source = exact_value(
        "capital_adequacy_ratio",
        "FY2025",
        page=84,
        label_contains="Capital to Risk Assets",
    )

    beta_proxy = 1.0
    base_cost_of_equity = cost_of_equity(beta_proxy, PH, 1.0)
    cases = {
        "bear": {
            "current_roe": max(ttm_roe - 0.01, 0.01),
            "cost_of_equity": base_cost_of_equity + 0.015,
            "terminal_roe": 0.115,
            "terminal_growth": 0.03,
        },
        "base": {
            "current_roe": ttm_roe,
            "cost_of_equity": base_cost_of_equity,
            "terminal_roe": 0.125,
            "terminal_growth": 0.035,
        },
        "bull": {
            "current_roe": ttm_roe + 0.005,
            "cost_of_equity": base_cost_of_equity - 0.01,
            "terminal_roe": 0.135,
            "terminal_growth": 0.04,
        },
    }
    results = {
        name: residual_income_valuation(
            book_value_per_share=book_value_per_share,
            current_roe=case["current_roe"],
            cost_of_equity=case["cost_of_equity"],
            current_payout_ratio=current_payout_ratio,
            terminal_roe=case["terminal_roe"],
            terminal_growth=case["terminal_growth"],
            years=5,
        )
        for name, case in cases.items()
    }

    source_map = {
        "parent_equity": parent_equity_source,
        "total_equity": total_equity_source,
        "total_assets": total_assets_source,
        "total_liabilities": total_liabilities_source,
        "customer_deposits": deposits_source,
        "net_loans": net_loans_source,
        "gross_loans": gross_loans_source,
        "allowance_credit_losses": {
            "method": "derived",
            "formula": "gross loans and receivables less net loans and receivables",
            "sources": [gross_loans_source, net_loans_source],
        },
        "cash": cash_source,
        "shares_outstanding": shares_source,
        "preferred_shares": preferred_source,
        "beginning_parent_equity": q2_2025_equity_source,
        "fy2025_parent_income": fy2025_income_source,
        "h1_2026_parent_income": h1_2026_income_source,
        "h1_2025_parent_income": h1_2025_income_source,
        "fy2025_net_interest_income": fy2025_nii_source,
        "h1_2026_net_interest_income": h1_2026_nii_source,
        "h1_2025_net_interest_income": h1_2025_nii_source,
        "dividends_paid": dividends_paid_source,
        "ttm_dividend_per_share": fy2025_dps_source,
        "cet1_ratio": cet1_source,
        "capital_adequacy_ratio": car_source,
    }
    normalized_inputs = {
        "as_of": "2026-06-30",
        "parent_equity": parent_equity,
        "preferred_par_capital": preferred_par_capital,
        "common_equity": common_equity,
        "book_value_per_share": book_value_per_share,
        "shares_outstanding": shares,
        "net_income": ttm_parent_income,
        "ttm_parent_net_income": ttm_parent_income,
        "ttm_eps": ttm_eps,
        "ttm_roe": ttm_roe,
        "net_interest_income": ttm_net_interest_income,
        "ttm_dividend_per_share": ttm_dividend_per_share,
        "dividends_paid": dividends_paid,
        "current_payout_ratio": current_payout_ratio,
        "total_assets": total_assets,
        "total_liabilities": total_liabilities,
        "total_equity": total_equity,
        "customer_deposits": deposits,
        "net_loans": net_loans,
        "gross_loans": gross_loans,
        "allowance_credit_losses": allowance_credit_losses,
        "cash": cash,
        "cet1_ratio": cet1,
        "capital_adequacy_ratio": car,
    }
    assumptions = {
        "beta_proxy": beta_proxy,
        "country_risk_exposure": 1.0,
        "risk_free_rate": PH.risk_free_rate,
        "mature_market_erp": PH.equity_risk_premium,
        "country_risk_premium": PH.country_risk_premium,
        "base_cost_of_equity": base_cost_of_equity,
        "assumptions_as_of": PH.assumptions_as_of,
        "assumptions_source": PH.assumptions_source,
        "terminal_roe": cases["base"]["terminal_roe"],
        "terminal_growth": cases["base"]["terminal_growth"],
        "forecast_years": 5,
    }
    audit_result = {
        "schema_version": "1.0",
        "ticker": "BDO",
        "company_name": "BDO Unibank, Inc.",
        "pse_sector": "Financials",
        "pse_subsector": "Banks",
        "classification_method": requirements["routing"]["method"],
        "financial_period": "TTM through Q2 2026",
        "valuation_date": "2026-06-30",
        "models_executed": [
            "residual_income",
            "clean_surplus_ddm",
            "justified_price_to_book",
        ],
        "models_not_executed": {
            "peer_price_to_book": "No contemporaneous public peer-price dataset was supplied to this filing-only test.",
            "regulatory_capital_fcfe": "Risk-weighted assets and a forecast regulatory-capital schedule were not sufficiently extracted.",
        },
        "parser_requirement_summary": requirements["summary"],
        "transformation_validation": {
            "required_total": 15,
            "required_transformed": 15,
            "missing_after_transformation": [],
            "reviewed_or_derived": [
                "shares_outstanding",
                "gross_loans",
                "allowance_credit_losses",
                "book_value_per_share",
            ],
        },
        "normalized_inputs": normalized_inputs,
        "assumptions": assumptions,
        "scenarios": results,
        "source_map": source_map,
        "warnings": [
            "Beta 1.0 is a disclosed bank-sector fallback, not a measured BDO regression beta.",
            "Preferred equity is proxied at disclosed PHP10 par value times 618m preferred shares.",
            "Credit-loss allowance is derived as gross loans from the loan note less net loans on the statement of financial position.",
            "The latest TTM dividend of PHP4.40 is reconstructed from declared common dividends and H1 cash dividends.",
            "The DDM reconciliation is mathematically linked to residual income through clean-surplus accounting.",
            "No current PSE market price is published or used in the intrinsic-value calculation.",
        ],
    }
    write_json(VALUATION_OUTPUT, audit_result)

    company = {
        "symbol": "BDO",
        "name": "BDO Unibank, Inc.",
        "shortName": "BDO Unibank",
        "sector": "Financials",
        "subsector": "Banks",
        "color": "#003b73",
        "dataConfidence": 0.9,
        "insight": (
            "BDO remains profitable and well-capitalized; the valuation depends "
            "mainly on sustainable ROE relative to the cost of equity."
        ),
        "source": {
            "label": "Nine BDO 17-A/17-Q filings through 30 June 2026",
            "href": "/data/bdo-filing-pipeline.json",
        },
        "financials": {
            "period": "FY 2025",
            "fiscalYear": 2025,
            "periodEnd": "2025-12-31",
            "revenue": None,
            "grossProfit": None,
            "operatingIncome": None,
            "generalAdmin": None,
            "interestExpense": None,
            "pretaxIncome": None,
            "taxExpense": None,
            "netIncome": fy2025_parent_income,
            "parentNetIncome": fy2025_parent_income,
            "cash": cash,
            "debt": None,
            "liabilities": total_liabilities,
            "equity": common_equity,
            "retainedEarnings": None,
            "retainedEarningsPrevious": None,
            "treasuryStock": None,
            "preferredStock": preferred_par_capital,
            "eps": fy2025_parent_income / shares,
            "epsPrevious": 82_000_000_000 / 5_272_257_961,
            "shares": shares,
            "operatingCashFlow": None,
            "source": {
                "label": "BDO FY2025 17-A",
            },
        },
        "financialHistory": {
            "annual": [
                {
                    "period": "FY 2024",
                    "fiscalYear": 2024,
                    "periodEnd": "2024-12-31",
                    "netIncome": 82_000_000_000,
                    "parentNetIncome": 82_000_000_000,
                    "eps": 15.48,
                    "dividendPerShare": 3.75,
                    "source": {"label": "BDO FY2024 17-A"},
                }
            ],
            "quarterly": [
                {
                    "period": "Q3 2025",
                    "fiscalYear": 2025,
                    "fiscalQuarter": 3,
                    "periodEnd": "2025-09-30",
                    "netIncome": 22_472_000_000,
                    "parentNetIncome": 22_472_000_000,
                    "eps": 22_472_000_000 / shares,
                    "dividendPerShare": 1.10,
                    "source": {"label": "BDO Q3 2025 17-Q"},
                },
                {
                    "period": "Q4 2025",
                    "fiscalYear": 2025,
                    "fiscalQuarter": 4,
                    "periodEnd": "2025-12-31",
                    "netIncome": fy2025_parent_income - 63_087_000_000,
                    "parentNetIncome": fy2025_parent_income - 63_087_000_000,
                    "eps": (fy2025_parent_income - 63_087_000_000) / shares,
                    "dividendPerShare": 1.10,
                    "source": {
                        "label": "Derived FY2025 less 9M 2025 filing",
                    },
                },
                {
                    "period": "Q1 2026",
                    "fiscalYear": 2026,
                    "fiscalQuarter": 1,
                    "periodEnd": "2026-03-31",
                    "netIncome": 20_112_000_000,
                    "parentNetIncome": 20_112_000_000,
                    "eps": 20_112_000_000 / shares,
                    "dividendPerShare": 1.10,
                    "source": {"label": "BDO Q1 2026 17-Q"},
                },
                {
                    "period": "Q2 2026",
                    "fiscalYear": 2026,
                    "fiscalQuarter": 2,
                    "periodEnd": "2026-06-30",
                    "netIncome": 20_611_000_000,
                    "parentNetIncome": 20_611_000_000,
                    "eps": 20_611_000_000 / shares,
                    "dividendPerShare": 1.10,
                    "cash": cash,
                    "liabilities": total_liabilities,
                    "equity": common_equity,
                    "preferredStock": preferred_par_capital,
                    "shares": shares,
                    "source": {"label": "BDO Q2 2026 17-Q"},
                },
            ],
        },
        "valuation": {
            "bank": {
                **normalized_inputs,
                "assumptions": assumptions,
                "scenarios": results,
            },
            "modelPolicy": {
                "primary": "residual_income",
                "crossChecks": ["ddm", "justified_pb"],
                "publishable": True,
                "reason": (
                    "Residual income is the primary bank model; DDM and justified "
                    "P/B are displayed as linked supporting checks."
                ),
                "warnings": audit_result["warnings"],
            },
            "note": (
                "Bank deposits are operating funding and are not treated as "
                "ordinary debt in an enterprise-value DCF."
            ),
        },
    }
    write_javascript_module(FRONTEND_OUTPUT, company)
    print(
        json.dumps(
            {
                "subsector": "Banks",
                "book_value_per_share": book_value_per_share,
                "ttm_roe": ttm_roe,
                "cost_of_equity": base_cost_of_equity,
                "base_residual_income": results["base"]["intrinsic_value"],
                "base_ddm": results["base"]["detail"]["ddm_cross_check"],
                "base_justified_pb": results["base"]["detail"][
                    "justified_pb_value"
                ],
                "frontend_output": str(FRONTEND_OUTPUT),
                "audit_output": str(VALUATION_OUTPUT),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
