#!/usr/bin/env python3
"""Build the Apple-first SEC filing valuation and FinSight UI snapshot."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.us_valuation import build_us_valuation  # noqa: E402
from app.us_valuation.sec_client import SecClient  # noqa: E402
from app.us_valuation.xbrl import load_concept_config  # noqa: E402


CIK = "0000320193"
OUTPUT_ROOT = ROOT / "output" / "us-testing" / "aapl"
FRONTEND_MODULE = (
    ROOT / "frontend" / "src" / "research" / "generated" / "apple-valuation.js"
)
FRONTEND_AUDIT = ROOT / "frontend" / "public" / "data" / "apple-valuation-pipeline.json"
BACKEND_RESULT = (
    ROOT / "backend" / "app" / "data" / "us_valuations" / "AAPL.json"
)
TEST_FIXTURE_ROOT = ROOT / "backend" / "tests" / "fixtures" / "us"


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def write_javascript_module(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        "// Generated by scripts/build_apple_us_valuation_pipeline.py.\n"
        "// Do not edit by hand; regenerate from the frozen SEC source cache.\n"
        f"export default {json.dumps(value, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def sec_cache_manifest(cache: Path) -> dict[str, Any]:
    records = []
    for name in (
        f"CIK{CIK}-submissions.json",
        f"CIK{CIK}-companyfacts.json",
    ):
        metadata_path = cache / f"{name}.meta.json"
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        records.append(
            {
                "cache_file": name,
                **metadata,
            }
        )
    return {
        "status": "frozen_sec_cache",
        "records": records,
    }


def slim_companyfacts(companyfacts: dict[str, Any]) -> dict[str, Any]:
    configured = load_concept_config()["fields"]
    required: dict[str, set[str]] = {}
    for definition in configured.values():
        for reference in definition["concepts"]:
            if ":" in reference:
                namespace, concept = reference.split(":", 1)
            else:
                namespace, concept = "us-gaap", reference
            required.setdefault(namespace, set()).add(concept)
    return {
        "cik": companyfacts["cik"],
        "entityName": companyfacts["entityName"],
        "facts": {
            namespace: {
                concept: companyfacts["facts"][namespace][concept]
                for concept in concepts
                if concept in companyfacts.get("facts", {}).get(namespace, {})
            }
            for namespace, concepts in required.items()
        },
    }


def slim_submissions(submissions: dict[str, Any]) -> dict[str, Any]:
    recent = submissions["filings"]["recent"]
    keep = (
        "accessionNumber",
        "filingDate",
        "reportDate",
        "acceptanceDateTime",
        "act",
        "form",
        "fileNumber",
        "filmNumber",
        "items",
        "size",
        "isXBRL",
        "isInlineXBRL",
        "primaryDocument",
        "primaryDocDescription",
    )
    return {
        key: submissions.get(key)
        for key in (
            "cik",
            "entityType",
            "sic",
            "sicDescription",
            "name",
            "tickers",
            "exchanges",
            "category",
            "fiscalYearEnd",
        )
    } | {
        "filings": {
            "recent": {key: recent.get(key, []) for key in keep},
            "files": [],
        }
    }


def public_result(
    result: dict[str, Any],
    submissions: dict[str, Any],
) -> dict[str, Any]:
    source = result["financials"]["ttm"]["sources"]["revenue"].get("current_ytd")
    if source is None:
        source = result["financials"]["ttm"]["sources"]["revenue"]["sources"][-1]
    recent = submissions["filings"]["recent"]
    source_index = recent["accessionNumber"].index(source["accession"])
    accession_compact = source["accession"].replace("-", "")
    cik_compact = str(int(result["issuer"]["cik"]))
    primary_document = recent["primaryDocument"][source_index]
    filing_url = (
        f"https://www.sec.gov/Archives/edgar/data/{cik_compact}/"
        f"{accession_compact}/{primary_document}"
    )
    assumptions = result["forecast_assumptions"]
    rate = result["discount_rate"]

    def public_model(model: dict[str, Any]) -> dict[str, Any]:
        return {
            "model": model["model"],
            "output_type": model["output_type"],
            "currency": model.get("currency", "USD"),
            "intrinsic_value_per_share": model.get("intrinsic_value_per_share"),
            "publication_state": model["publication_state"],
            "errors": model.get("errors", []),
            "warnings": model.get("warnings", []),
        }

    return {
        "schema_version": "US-PUBLIC-VALUATION-1.0",
        "valuation_date": result["valuation_date"],
        "market": "US",
        "currency": "USD",
        "issuer": {
            key: result["issuer"][key]
            for key in (
                "cik",
                "ticker",
                "issuer_name",
                "finsight_sector",
                "primary_archetype",
                "secondary_archetypes",
                "classification_confidence",
                "mapping_version",
                "classification_reason",
            )
        },
        "source_financial_statement": {
            "form": source["form"],
            "period_end": result["financial_period_end"],
            "filed_date": source["filed"],
            "accession": source["accession"],
            "url": filing_url,
            "note": "Latest financial statement used; this does not claim to be the issuer's latest disclosure of every type.",
        },
        "model_policy": result["model_policy"],
        "public_assumptions": {
            "forecast_policy_version": assumptions["forecast_policy_version"],
            "forecast_years": assumptions["forecast_years"],
            "forecast_mode": (
                assumptions["segment_forecast"]["mode"]
                if assumptions.get("segment_forecast")
                else "consolidated"
            ),
            "initial_revenue_growth": assumptions["initial_revenue_growth"],
            "target_operating_margin": assumptions["target_operating_margin"],
            "segment_assumptions": (
                {
                    key: {
                        "label": segment["label"],
                        "initial_revenue_growth": segment[
                            "initial_revenue_growth"
                        ],
                        "target_gross_margin": segment[
                            "target_gross_margin"
                        ],
                    }
                    for key, segment in assumptions[
                        "segment_forecast"
                    ]["segments"].items()
                }
                if assumptions.get("segment_forecast")
                else {}
            ),
            "sales_to_capital": assumptions["sales_to_capital"],
            "terminal_growth": assumptions["terminal_growth"],
            "discount_policy_version": rate["market_assumptions"]["policy_version"],
            "discount_calibration_type": rate["calibration_type"],
            "policy_wacc": rate["wacc"],
            "risk_free_rate": rate["market_assumptions"]["risk_free_rate"],
            "risk_free_effective_date": rate["market_assumptions"][
                "risk_free_effective_date"
            ],
            "risk_free_source_url": rate["market_assumptions"][
                "risk_free_source_url"
            ],
            "equity_risk_premium": rate["market_assumptions"][
                "equity_risk_premium"
            ],
        },
        "models": {
            key: public_model(model)
            for key, model in result["models"].items()
        },
        "scenarios": {
            name: {
                "fcff_dcf": public_model(scenario["fcff_dcf"]),
            }
            for name, scenario in result["scenarios"].items()
        },
        "scenario_range": result["scenario_range"],
        "forecast_quality": result["forecast_quality"],
        "review": result["review"],
        "methodology": result["methodology"],
        "data_boundary": {
            "raw_financial_statement_values_included": False,
            "stock_prices_used": False,
            "public_payload_contains": "derived valuation outputs, governed assumptions, methodology, warnings, and filing attribution",
        },
    }


def frontend_company(
    result: dict[str, Any],
    public: dict[str, Any],
) -> dict[str, Any]:
    financials = result["financials"]
    annual = [
        {
            "period": f"FY {row['fiscal_year']}",
            "fiscalYear": row["fiscal_year"],
            "periodEnd": row["period_end"],
            "source": {
                "label": "SEC annual filing period loaded",
            },
        }
        for row in financials["annual"]
    ]
    quarterly = [
        {
            "period": (
                f"FY {row['fiscal_year']} Q{row['fiscal_quarter']}"
            ),
            "fiscalYear": row["fiscal_year"],
            "fiscalQuarter": row["fiscal_quarter"],
            "periodEnd": row["period_end"],
            "source": {
                "label": "SEC stand-alone quarter reconstructed",
            },
        }
        for row in financials["quarterly"]["revenue"]
    ]
    return {
        "symbol": "AAPL",
        "name": result["issuer"]["issuer_name"],
        "shortName": "Apple",
        "market": "US",
        "currency": "USD",
        "sector": result["issuer"]["finsight_sector"],
        "subsector": "Hardware & electronic equipment",
        "archetype": result["issuer"]["primary_archetype"],
        "color": "#555555",
        "dataConfidence": 0.82,
        "insight": (
            "Apple is routed to a mature hardware-and-services FCFF model. "
            "The value is filing-only and does not use a stock price."
        ),
        "source": {
            "label": (
                "Latest financial statement used: Apple Form 10-Q for "
                f"{public['source_financial_statement']['period_end']}, filed "
                f"{public['source_financial_statement']['filed_date']}"
            ),
            "href": public["source_financial_statement"]["url"],
        },
        "financials": {
            "period": f"TTM ended {result['financial_period_end']}",
            "fiscalYear": int(result["financial_period_end"][:4]),
            "periodEnd": result["financial_period_end"],
            "source": {
                "label": "SEC filing periods loaded; raw amounts remain private",
            },
        },
        "financialHistory": {
            "annual": annual,
            "quarterly": quarterly,
        },
        "valuation": {
            "us": public,
            "modelPolicy": {
                "primary": "fcff_dcf",
                "crossChecks": ["epv"],
                "publishable": public["review"]["publication_state"] != "withheld",
                "reason": public["model_policy"]["reason"],
                "warnings": public["review"]["warnings"],
            },
            "note": (
                "The displayed range comes from filing-derived Apple inputs and "
                "governed public-economic assumptions. It excludes market price."
            ),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--refresh", action="store_true")
    parser.add_argument(
        "--valuation-date",
        default="2026-07-31",
    )
    args = parser.parse_args()

    cache = OUTPUT_ROOT / "sec-cache"
    client = SecClient(
        user_agent=os.environ.get("SEC_USER_AGENT"),
        cache_dir=cache,
    )
    submissions = client.submissions(CIK, refresh=args.refresh)
    companyfacts = client.companyfacts(CIK, refresh=args.refresh)
    source_manifest = sec_cache_manifest(cache)
    result = build_us_valuation(
        submissions=submissions,
        companyfacts=companyfacts,
        valuation_date=args.valuation_date,
        source_manifest=source_manifest,
    )
    public = public_result(result, submissions)
    frontend = frontend_company(result, public)

    write_json(OUTPUT_ROOT / "valuation-result.json", result)
    write_json(FRONTEND_AUDIT, public)
    write_json(BACKEND_RESULT, public)
    write_javascript_module(FRONTEND_MODULE, frontend)
    write_json(TEST_FIXTURE_ROOT / "aapl-submissions.json", slim_submissions(submissions))
    write_json(TEST_FIXTURE_ROOT / "aapl-companyfacts.json", slim_companyfacts(companyfacts))

    print(
        json.dumps(
            {
                "ticker": result["issuer"]["ticker"],
                "period_end": result["financial_period_end"],
                "primary_model": result["model_policy"]["primary"],
                "supporting_models": result["model_policy"]["supporting"],
                "scenario_range": result["scenario_range"],
                "review": result["review"],
                "outputs": [
                    str(OUTPUT_ROOT / "valuation-result.json"),
                    str(FRONTEND_MODULE),
                    str(FRONTEND_AUDIT),
                    str(BACKEND_RESULT),
                ],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
