"""Public-safe and frontend artifacts for filing-only U.S. valuations."""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any

from .sec_client import normalize_cik
from .xbrl import load_concept_config


def write_json(path: Path, value: Any) -> None:
    """Atomically write a JSON artifact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def write_javascript_module(path: Path, value: Any, *, generator: str) -> None:
    """Atomically write a generated frontend module."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        f"// Generated by {generator}.\n"
        "// Do not edit by hand; regenerate from the frozen SEC source cache.\n"
        f"export default {json.dumps(value, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def sec_cache_manifest(cache: Path, cik: str | int) -> dict[str, Any]:
    """Return durable provenance metadata for both SEC source responses."""
    normalized = normalize_cik(cik)
    records = []
    for name in (
        f"CIK{normalized}-submissions.json",
        f"CIK{normalized}-companyfacts.json",
    ):
        metadata_path = cache / f"{name}.meta.json"
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        records.append({"cache_file": name, **metadata})
    return {"status": "frozen_sec_cache", "records": records}


def slim_companyfacts(companyfacts: dict[str, Any]) -> dict[str, Any]:
    """Keep only SEC concepts the normalizer needs for a reproducible fixture."""
    required: dict[str, set[str]] = {}
    for definition in load_concept_config()["fields"].values():
        for reference in definition["concepts"]:
            namespace, separator, concept = reference.partition(":")
            if not separator:
                namespace, concept = "us-gaap", namespace
            required.setdefault(namespace, set()).add(concept)
    return {
        "cik": companyfacts["cik"],
        "entityName": companyfacts["entityName"],
        "facts": {
            namespace: {
                concept: companyfacts["facts"][namespace][concept]
                for concept in concepts
                if concept in companyfacts.get("facts", {}).get(namespace, {})
            }
            for namespace, concepts in required.items()
        },
    }


def slim_submissions(submissions: dict[str, Any]) -> dict[str, Any]:
    """Keep filing identity fields needed to attribute the valuation period."""
    recent = submissions["filings"]["recent"]
    keep = (
        "accessionNumber",
        "filingDate",
        "reportDate",
        "acceptanceDateTime",
        "act",
        "form",
        "fileNumber",
        "filmNumber",
        "items",
        "size",
        "isXBRL",
        "isInlineXBRL",
        "primaryDocument",
        "primaryDocDescription",
    )
    return {
        key: submissions.get(key)
        for key in (
            "cik",
            "entityType",
            "sic",
            "sicDescription",
            "name",
            "tickers",
            "exchanges",
            "category",
            "fiscalYearEnd",
        )
    } | {"filings": {"recent": {key: recent.get(key, []) for key in keep}, "files": []}}


def _source_financial_statement(
    result: dict[str, Any], submissions: dict[str, Any]
) -> dict[str, Any]:
    revenue_source = result["financials"]["ttm"]["sources"]["revenue"]
    source = revenue_source.get("current_ytd")
    if source is None:
        source = revenue_source.get("sources", [{}])[-1]
    recent = submissions.get("filings", {}).get("recent", {})
    accessions = recent.get("accessionNumber", [])
    accession = source.get("accession")
    source_index = accessions.index(accession) if accession in accessions else None
    primary_documents = recent.get("primaryDocument", [])
    primary_document = (
        primary_documents[source_index]
        if source_index is not None and source_index < len(primary_documents)
        else None
    )
    filing_url = None
    if accession and primary_document:
        filing_url = (
            "https://www.sec.gov/Archives/edgar/data/"
            f"{int(result['issuer']['cik'])}/{accession.replace('-', '')}/{primary_document}"
        )
    return {
        "form": source.get("form"),
        "period_end": result["financial_period_end"],
        "filed_date": source.get("filed"),
        "accession": accession,
        "url": filing_url,
        "note": "Latest financial statement used; this does not claim to be the issuer's latest disclosure of every type.",
    }


def _public_model(model: dict[str, Any]) -> dict[str, Any]:
    return {
        "model": model["model"],
        "output_type": model["output_type"],
        "currency": model.get("currency", "USD"),
        "intrinsic_value_per_share": model.get("intrinsic_value_per_share"),
        "publication_state": model["publication_state"],
        "errors": model.get("errors", []),
        "warnings": model.get("warnings", []),
    }


PUBLICATION_STATES = {"pass", "review_required", "withheld"}


def sanitize_public_artifact(artifact: dict[str, Any]) -> dict[str, Any]:
    """Validate public state vocabulary and fail closed at every serving boundary."""
    public = deepcopy(artifact)
    review = public.get("review")
    if not isinstance(review, dict):
        review = {}
        public["review"] = review
    state = review.get("publication_state")
    invalid_state = state not in PUBLICATION_STATES
    for model in public.get("models", {}).values():
        if not isinstance(model, dict) or model.get("publication_state") not in PUBLICATION_STATES:
            invalid_state = True
    for scenario in public.get("scenarios", {}).values():
        # Scenarios are keyed by model name (fcff_dcf, residual_income, ddm, ...);
        # validate whichever model each scenario carries.
        scenario_models = list(scenario.values()) if isinstance(scenario, dict) else []
        if not scenario_models:
            invalid_state = True
        for model in scenario_models:
            if not isinstance(model, dict) or model.get("publication_state") not in PUBLICATION_STATES:
                invalid_state = True
    if invalid_state:
        review["publication_state"] = "withheld"
        review.setdefault("errors", []).append(
            "Public artifact has an unsupported publication state and was withheld."
        )
    if review["publication_state"] != "withheld":
        return public
    models = public.setdefault("models", {})
    scenarios = public.setdefault("scenarios", {})
    for model in models.values():
        model["intrinsic_value_per_share"] = None
        model["publication_state"] = "withheld"
    for scenario in scenarios.values():
        for scenario_model in (scenario.values() if isinstance(scenario, dict) else []):
            if isinstance(scenario_model, dict):
                scenario_model["intrinsic_value_per_share"] = None
                scenario_model["publication_state"] = "withheld"
    public["scenario_range"] = {
        "low": None,
        "base": None,
        "high": None,
            "label": public.get("scenario_range", {}).get(
            "label", "assumption range, not a statistical confidence interval"
        ),
    }
    # Sensitivities are not part of the current public schema. Keep this branch
    # defensive so a future public extension cannot bypass the fail-closed gate.
    for row in public.get("sensitivities", []):
        row["intrinsic_value_per_share"] = None
        row["publication_state"] = "withheld"
    return public


def public_result(result: dict[str, Any], submissions: dict[str, Any]) -> dict[str, Any]:
    """Convert a private valuation result into a raw-statement-free artifact."""
    assumptions = result["forecast_assumptions"]
    discount_rate = result["discount_rate"]
    market_assumptions = discount_rate["market_assumptions"]
    segment_forecast = assumptions.get("segment_forecast")
    forecast_mode = (
        segment_forecast["mode"]
        if segment_forecast
        else (
            "unavailable"
            if assumptions.get("forecast_evidence_status")
            == "unavailable_for_normalized_period"
            else "consolidated"
        )
    )
    segment_assumptions = (
        {
            key: {
                "label": segment["label"],
                "initial_revenue_growth": segment["initial_revenue_growth"],
                "target_operating_margin": segment.get("target_operating_margin"),
                "target_gross_margin": segment.get("target_gross_margin"),
            }
            for key, segment in segment_forecast["segments"].items()
        }
        if segment_forecast
        else {}
    )
    public = {
        "schema_version": "US-PUBLIC-VALUATION-1.0",
        "valuation_date": result["valuation_date"],
        "market": "US",
        "currency": "USD",
        "ticker": result["issuer"]["ticker"],
        "issuer": {
            key: result["issuer"][key]
            for key in (
                "cik",
                "ticker",
                "issuer_name",
                "finsight_sector",
                "primary_archetype",
                "secondary_archetypes",
                "classification_confidence",
                "mapping_version",
                "classification_reason",
            )
        },
        "source_financial_statement": _source_financial_statement(
            result, submissions
        ),
        "model_policy": result["model_policy"],
        "public_assumptions": {
            "forecast_policy_version": assumptions.get("forecast_policy_version"),
            "forecast_years": assumptions.get("forecast_years"),
            "forecast_mode": forecast_mode,
            "initial_revenue_growth": assumptions.get("initial_revenue_growth"),
            "target_operating_margin": assumptions.get("target_operating_margin"),
            "segment_assumptions": segment_assumptions,
            "sales_to_capital": assumptions.get("sales_to_capital"),
            "terminal_growth": assumptions.get("terminal_growth"),
            "discount_policy_version": market_assumptions["policy_version"],
            "discount_calibration_type": discount_rate["calibration_type"],
            "policy_wacc": discount_rate["wacc"],
            "risk_free_rate": market_assumptions["risk_free_rate"],
            "risk_free_effective_date": market_assumptions[
                "risk_free_effective_date"
            ],
            "risk_free_source_url": market_assumptions["risk_free_source_url"],
            "equity_risk_premium": market_assumptions["equity_risk_premium"],
        },
        "models": {key: _public_model(model) for key, model in result["models"].items()},
        "scenarios": {
            name: {"fcff_dcf": _public_model(scenario["fcff_dcf"])}
            for name, scenario in result["scenarios"].items()
        },
        "scenario_range": result["scenario_range"],
        "forecast_quality": result["forecast_quality"],
        "review": result["review"],
        "methodology": result["methodology"],
        "data_boundary": {
            "raw_financial_statement_values_included": False,
            "stock_prices_used": False,
            "public_payload_contains": "derived valuation outputs, governed assumptions, methodology, warnings, and filing attribution",
        },
    }
    return sanitize_public_artifact(public)


def frontend_company(
    result: dict[str, Any], public: dict[str, Any], issuer_metadata: dict[str, Any]
) -> dict[str, Any]:
    """Build a frontend record without copying private filing amounts."""
    financials = result["financials"]
    annual = [
        {
            "period": f"FY {row['fiscal_year']}",
            "fiscalYear": row["fiscal_year"],
            "periodEnd": row["period_end"],
            "source": {"label": "SEC annual filing period loaded"},
        }
        for row in financials["annual"]
    ]
    quarterly = [
        {
            "period": f"FY {row['fiscal_year']} Q{row['fiscal_quarter']}",
            "fiscalYear": row["fiscal_year"],
            "fiscalQuarter": row["fiscal_quarter"],
            "periodEnd": row["period_end"],
            "source": {"label": "SEC stand-alone quarter reconstructed"},
        }
        for row in financials["quarterly"]["revenue"]
    ]
    short_name = issuer_metadata["short_name"]
    source = public["source_financial_statement"]
    source_label = issuer_metadata.get(
        "source_label",
        f"Latest financial statement used: {short_name} Form {source['form']} for {source['period_end']}, filed {source['filed_date']}",
    )
    valuation_note = issuer_metadata.get(
        "valuation_note",
        f"The displayed range comes from filing-derived {short_name} inputs and governed public-economic assumptions. It excludes market price.",
    )
    return {
        "symbol": issuer_metadata.get("ticker", result["issuer"]["ticker"]),
        "name": result["issuer"]["issuer_name"],
        "shortName": short_name,
        "market": "US",
        "currency": "USD",
        "sector": result["issuer"]["finsight_sector"],
        "subsector": issuer_metadata["subsector"],
        "archetype": result["issuer"]["primary_archetype"],
        "color": issuer_metadata.get("color", "#555555"),
        "dataConfidence": issuer_metadata.get("data_confidence", 0.82),
        "insight": issuer_metadata["insight"],
        "source": {"label": source_label, "href": source["url"]},
        "financials": {
            "period": f"TTM ended {result['financial_period_end']}",
            "fiscalYear": int(result["financial_period_end"][:4]),
            "periodEnd": result["financial_period_end"],
            "source": {"label": "SEC filing periods loaded; raw amounts remain private"},
        },
        "financialHistory": {"annual": annual, "quarterly": quarterly},
        "valuation": {
            "us": public,
            "modelPolicy": {
                "primary": "fcff_dcf",
                "crossChecks": ["epv"],
                "publishable": public["review"]["publication_state"] != "withheld",
                "reason": public["model_policy"]["reason"],
                "warnings": public["review"]["warnings"],
            },
            "note": valuation_note,
        },
    }
